import os
import env_var


BOT_TOKEN = env_var.BOT_TOKEN
BOT_USERNAME = env_var.BOT_USERNAME
SMTP_SERVER = env_var.SMTP_SERVER
SMTP_PORT = env_var.SMTP_PORT
SMTP_USERNAME = env_var.SMTP_USERNAME
SMTP_PASSWORD = env_var.SMTP_PASSWORD
SMTP_SENDER = env_var.SMTP_SENDER
